// Generated by Wrangler by running `wrangler types`

interface Env {
	STRAVA_API_URL: "https://www.strava.com/api";
	STRAVA_CLUB_ID: "1460333";
	STRAVA_CLIENT_ID: string;
	STRAVA_CLIENT_SECRET: string;
	STRAVA_ACCESS_TOKEN: string;
	STRAVA_REFRESH_TOKEN: string;
	API_SECRET_KEY: string;
	db: D1Database;
}
