#:schema node_modules/wrangler/config-schema.json
name = "remix-cloudflare-workers-template"

main = "./server.ts"
workers_dev = true
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2024-09-26"

[assets]
# https://developers.cloudflare.com/workers/static-assets/binding/
directory = "./build/client"

[build]
command = "npm run build"

[[d1_databases]]
binding = "db"
database_name = "geekbike"
database_id = "2f66ae09-b510-4fd0-be3c-23697273846f"

[vars]
STRAVA_API_URL = "https://www.strava.com/api"
STRAVA_CLUB_ID = "1460333"